import "./cache/list";
import "./cache/clean";
import "./help";
import "./home";
import "./info";
import "./init";
import "./install";
import "./list";
import "./link";
import "./lookup";
import "./prune";
import "./register";
import "./search";
import "./uninstall";
import "./update";
import "./version";
import "./bower";
describe('integration tests', function() {});
